import type { Metadata } from "next";
import { Inria_Serif, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inriaSerif = Inria_Serif({
  variable: "--font-inria-serif",
  subsets: ["latin"],
  weight: ["400", "700"], 
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Restaurant",
  description: "Generated by create next app",
};





export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inriaSerif.variable} ${playfairDisplay.variable} h-full antialiased`}>



      <body className="min-h-full flex flex-col">
      <Navbar></Navbar>
        {children}


      </body>



    </html>
  );
}
